# Generated by Django 4.1.1 on 2022-10-02 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import efficiency.models


class Migration(migrations.Migration):

    dependencies = [
        ('efficiency', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hours_assigned', models.FloatField()),
                ('hours_present', models.FloatField(default=0.0)),
                ('type', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, unique=True)),
                ('description', models.TextField(blank=True, max_length=1023, null=True)),
                ('status', models.PositiveIntegerField(default=0)),
                ('deadline', models.DateTimeField()),
                ('no_of_employees', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=31)),
                ('long', models.CharField(max_length=31)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('log_picture', models.ImageField(blank=True, upload_to=efficiency.models.upload_log_handler)),
                ('log_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efficiency.attendance')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, max_length=1023, null=True)),
                ('for_project', models.BooleanField(default=False)),
                ('due_time', models.DateTimeField()),
                ('closing_time', models.DateTimeField()),
                ('is_complete', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_by', to='efficiency.profile')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_to', to='efficiency.profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='efficiency.project')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(max_length=1023)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_given_for', to='efficiency.profile')),
                ('given_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_given_by', to='efficiency.profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='efficiency.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efficiency.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efficiency.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efficiency.profile'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, max_length=1023, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver', to='efficiency.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to='efficiency.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, max_length=1023, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('mode', models.CharField(max_length=127)),
                ('for_project', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_created_by', to='efficiency.profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='efficiency.project')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=31)),
                ('long', models.CharField(max_length=31)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efficiency.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FingerPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger_type', models.CharField(max_length=15)),
                ('finger_hand', models.CharField(max_length=15)),
                ('fingerprint', models.ImageField(blank=True, upload_to=efficiency.models.upload_path_handler)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efficiency.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Efficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficiency', models.FloatField(default=0.0)),
                ('month', models.CharField(max_length=15)),
                ('year', models.PositiveIntegerField(default=2022)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efficiency.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efficiency.profile')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efficiency.meeting')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efficiency.profile'),
        ),
    ]
