# Generated by Django 3.2.8 on 2023-03-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efficiency', '0004_auto_20230319_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Team Leader', 'Team Leader'), ('Admin', 'Admin')], default='Employee', max_length=15),
        ),
    ]
