# Generated by Django 3.2.8 on 2023-03-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efficiency', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('1', 'Employee'), ('2', 'Team Leader'), ('3', 'Admin')], default='1', max_length=15),
        ),
    ]
