# Generated by Django 4.1.1 on 2023-03-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("efficiency", "0006_alter_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Employee", "Employee"),
                    ("Team Leader", "Team Leader"),
                    ("Admin", "Admin"),
                ],
                default="1",
                max_length=15,
            ),
        ),
    ]
